module.exports = {
    title: {
        yewu: 'Courier Service',
        yunfei: 'Calculation',
        aboutus: 'About Us',
        faq: 'FAQ',
        usercenter: 'Personal Center',
        register: 'Register',
        login: 'Login',
    },
    index: {
        xiadan: 'Order',
        xingcheng: 'Create a trip',
        wsmashi: "Why choose ashibro",
        zrsd: 'Express delivery',
        zrsdintro: 'Logistics structured by global passengers to ensure the fastest speed of goods to reach the destination.',
        jgsh: "Affordable",
        jgshintro: 'Lower than the service price of international logistics industry Ge, enjoy the standard higher than the industry service.',
        wdds: "Countier service",
        wddsintro: 'Ashibro has set up courtier service in many countries.',
        jskf: 'Instant customer service',
        jskfintro: 'Any questions about the your delivery can be answered through contact customer service directly via wechat.',
        tggxjsintro: 'Make every journey affordable through the sharing your luggage allowance',
        q_jdnzsm: 'What can ashibro do?',
        q_fwbhgs: 'Does the service include tariffs?',
        q_nxbn: "Which items can't be transported by ashibro?",
        q_dxjd: 'What if package lost or broken?',
        q_yfjs: 'How is the cost calculated?',
        q_sxx: 'Time effection of ashibro?',
        gdcj: 'More information',
        lxwm: 'Contact us:',
        dianhua: 'Tele',
        youxiang: 'Email',
        dizhi: 'Add',
    }
}