module.exports = {
    title: {
        yewu: '业务网点',
        yunfei: '运费计算',
        aboutus: '关于我们',
        faq: 'FAQ',
        usercenter: '个人中心',
        register: '注册',
        login: '登录',
    },
    index: {
        xiadan: '我要下单',
        xingcheng: '创建行程',
        wsmashi: "为什么选择ashibro",
        zrsd: '专人速递',
        zrsdintro: '由全球旅客构架而成的物流网络，确保货物以最快的速度到达目的地。',
        jgsh: "价格实惠",
        jgshintro: '低于国际物流行业服务的价格，享受高于行业服务的标准。',
        wdds: "网点代收",
        wddsintro: '脚递在多国设有业务网点，代收代寄，为您的订单提供保障。',
        jskf: '即时客服',
        jskfintro: '关于业务的任何问题，都可通过微信或者站内信直接联系客服，快速解决。',
        tggxjsintro: '通过共享经济模式，让您的每一次旅程无负担',
        q_jdnzsm: '脚递ashibro能为你做什么？',
        q_fwbhgs: '服务是否包含关税？',
        q_nxbn: "那些物品不能使用脚递运输？",
        q_dxjd: '东西寄丢寄坏了怎么办？',
        q_yfjs: '费用如何计算？',
        q_sxx: 'ashibro的时效性？',
        gdcj: '更多常见问题',
        lxwm: '联系我们',
        dianhua: '电话',
        youxiang: '邮箱',
        dizhi: '地址',
    }
}